Project:
  name: 'MgNOv6.3'
  experiment: 'MgNOv6.3'
  checkpoint: False
  save_top_k: 3
  erase: True
  do: 'train'
  devices: 4
  accelerator: 'gpu'
  save: True
  save_path: '/ibex/user/liux0t/AI4S-cupv2' 


data:
  PATH_data: "/ibex/user/liux0t"  # 数据集路径，这里只提供示例
  PATH_target: "/ibex/user/liux0t"
  train_num: 7100
  valid_num: 100
  load_workers: 40
  frequency: 7
  batch: 10
  size: 480

   
model:
  name: "MgNOv6.3"
  wavenumber: [40, 40, 40,40,40,40,40]
  features: 40
  padding: 32
  loss: 'rel_l2'

  


  

train:
  batchsize: 10
  epochs: 15
  lr: 0.001
  step_size: 100
  gamma: 0.5
  weight_decay: 0.00001
  eta_min: 0.0005
  add_term: True




ckpt:
  PATH: "save_files"
  save_dir: 'MgNOv6.3'
  alias: 'MgNOv6.3'