Project:
  name: 'MgNOv7.2'
  experiment: 'MgNOv7.2'
  checkpoint: False
  save_top_k: 3
  erase: False
  do: 'test'
  fine_tune: True
  devices: 1
  accelerator: 'gpu'
  save: True
  save_path: '/ibex/user/liux0t/AI4S-cupv2' 


data:
  PATH_data: "/ibex/user/liux0t"  # 数据集路径，这里只提供示例
  PATH_target: "/ibex/user/liux0t"
  train_num: 6900
  valid_num: 10
  load_workers: 40
  frequency: 7
  batch: 10
  size: 480

   
model:
  name: "MgNOv7.2"
  iteration: 6
  features: 24
  loss: 'rel_l2' # rel_l2

  

train:
  batchsize: 10
  epochs: 10
  lr: 0.000005
  step_size: 100
  gamma: 0.5
  weight_decay: 0.0 #0001
  eta_min: 0.0005
  add_term: True




ckpt:
  PATH: "save_files"
  save_dir: 'MgNOv7.2'
  alias: 'MgNOv7.2'